name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: rustup target add x86_64-unknown-linux-musl && sudo apt-get update && sudo apt-get install -y musl-tools
    - name: Build
      run: RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: target/x86_64-unknown-linux-musl/release/rustaman
 
